Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -28,10 +28,11 @@ jobs:
 
       - name: Make list.txt file
         run: |
-          cd code || { echo "Directory ./code not found"; exit 1; }
+          cd code/data || { echo "Directory ./code not found"; exit 1; }
           ls -p | grep -v / > list.txt
           cd ../
-          mv code/list.txt .
+          mv code/data/list.txt .
+          rm code/data/list.txt
 
       - name: Build dlc.dat file
         run: |
